version: '3.1'

services:
  db:
    build: .
    container_name: nestproject-db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nestproject

  dbtest:
    build: .
    container_name: test-db
    restart: always
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nestproject
